{% set name = "immutables" %}
{% set version = "0.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3713ab1ebbb6946b7ce1387bb9d1d7f5e09c45add58c2a2ee65f963c171e746b

build:
  skip: true  # [py27]
  number: 0
  script: python -m pip install . --no-deps --ignore-installed

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools
  run:
    - python

test:
  requires:
    - pytest
  source_files:
    - tests
  imports:
    - immutables
  commands:
    - pytest tests

about:
  home: https://github.com/MagicStack/immutables
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Immutable Collections
  description: An immutable mapping type for Python.
  dev_url: https://github.com/MagicStack/immutables

extra:
  recipe-maintainers:
    - nicoddemus
